name: Resumen Diario Foro
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  scraping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar Playwright
        run: |
          pip install playwright requests
          playwright install chromium
      - name: Ejecutar Script
        env:
          USER_CONMIGENTE: ${{ secrets.USER_CONMIGENTE }}
          PASS_CONMIGENTE: ${{ secrets.PASS_CONMIGENTE }}
        run: python script_foro.py
